### ISSUE TITLE
Dependency Question

### ISSUE THREAD

**Issue by nephatrine** [Saereth/nocturnal#1]
Trying to use nocturnal-1.0.jar from CurseForge. Only required dependencies I see listed on there are Thaumcraft and Defiled Lands, but the game won't start because I'm missing GuideAPI and Blood Magic. Are those intended to be hard requirements or optional?

**Comment by Saereth** [comment]
They are not intended to be hard dependencies, will fix that up shortly. Added some new features and stuff as well, expect an updated version out with that fix and the new stuff by this weekend

**Comment by Saereth** [comment]
new version isnt dependant on anything except thaumcraft, will be uploading later today.

**Comment by Saereth** [comment]
fixed via https://github.com/Saereth/nocturnal/commit/1841e2f6f22a75d94993822fd535a4feddecc659
